server:
  port: 8888
spring:
  application:
    name: erudio-config-server

  ## Usado para dados de application.yml local
  #profiles:
  #  active:
  #   - native

  ## Usado para pegar dados na Cloud
  cloud:
    config:
      server:
        git:
          uri: https://github.com/sauloPereira/test-config-server.git
          #username: username
          #password: password
          default-label: main
          search-paths:
            - 'greeting-service*'

